services:
  nginx:
    build:
      args:
        - SERVER_NAME=${SERVER_NAME}
      context: app/nginx
      dockerfile: dockerfile
    image: nginx
    container_name: nginx-container
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception_network

  wordpress:
    build:
      args:
        - SERVER_NAME=${SERVER_NAME}
        - MYSQL_DB_HOST=${MYSQL_DB_HOST}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      context: app/wordpress
      dockerfile: dockerfile
    image: dockerfile
    container_name: wordpress-container
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception_network
  
  mariadb:
    build:
      context: app/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    image: mariadb
    container_name: mariadb-container
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - maria-database:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/mister-coder/data/wordpress
      o: bind

  maria-database:
    driver: local
    driver_opts:
      type: none
      device: /home/mister-coder/data/mariadb
      o: bind

networks:
  inception_network:
    driver: bridge
